Added in feature for missed fullscreen mode
cgkineo/adapt-youtube pull request #7
Opened 2018-12-11 14:50 UTC by mike-st

2018-12-11 16:06 UTC, moloko requested changes
thanks for doing this, few minor changes needed - have done github 'suggestions' so they should be quick to implement

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "inputType": {"type": "Boolean", "options": [true, false]},
```suggestion
          "inputType": "Checkbox",
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "help": "This parameter lets you use the fullscreen function on a Youtube video. When press the video will fill the screen."
typo "When press the video"... however, I don't think you really need help for this entry, the title's descriptive enough

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "inputType": {"type": "Boolean", "options": [true, false]},
```suggestion
          "inputType": "Checkbox",
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "help": "This tells to set this video to complete when the inline transcript is shown"
```suggestion
          "help": "Whether to have this component mark as completed when the transcript is shown."
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "inputType": {"type": "Boolean", "options": [true, false]},
```suggestion
          "inputType": "Checkbox",
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "inputType": {"type": "Boolean", "options": [true, false]},
```suggestion
          "inputType": "Checkbox",
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +          "title": "Set Completion",
```suggestion
          "title": "Trigger completion?",
```

2018-12-11 16:06 UTC, moloko commented on properties.schema
> +      "help": "Tells when to set this video to complete"
```suggestion
      "help": "Which event should trigger completion of this component."
```

2018-12-11 16:06 UTC, moloko commented on templates/youtube.hbs
> +		<iframe width="640px" height="360px" style="width:100%;" src="{{_media._source}}?&autoplay={{#if _media._autoplay}}1{{else}}0{{/if}}&rel={{#if _media._showRelated}}1{{else}}0{{/if}}&loop={{#if _loo
the attribute `allowfullscreen` should have the value `"true"` - source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes

```suggestion
		<iframe width="640px" height="360px" style="width:100%;" src="{{_media._source}}?&autoplay={{#if _media._autoplay}}1{{else}}0{{/if}}&rel={{#if _media._showRelated}}1{{else}}0{{/if}}&loop={{#if _loop}}1{{else}}0{{/if}}&modestbranding={{#if _media._modestBranding}}1{{else}}0{{/if}}&color={{#if _media._progressColor}}{{_media._progressColor}}{{/if}}&controls=3&enablejsapi=1&playsinline=1&showinfo=0&iv_load_policy={{#if _media._showAnnotations}}1{{else}}3{{/if}}" frameborder="0" {{#if _media._allowFullscreen}}allowfullscreen="true"{{/if}}></iframe>
```

2018-12-11 16:06 UTC, moloko commented on js/adapt-youtube.js
> +            var $button = this.$(".youtube-inline-transcript-button");
You've got [this bug](https://github.com/adaptlearning/adapt_framework/issues/2062) here... you can fix by doing this:
```suggestion
            var $buttonText = this.$(".youtube-inline-transcript-button .transcript-text-container");
```
then changing the instances of `$button` on L105 and L111 to `$buttonText`

2018-12-11 16:06 UTC, moloko commented on js/adapt-youtube.js
> +                $transcriptBodyContainer.slideUp(function() {
You've got [this bug](https://github.com/adaptlearning/adapt_framework/issues/1718) here, you can fix by doing:
```suggestion
                $transcriptBodyContainer.stop(true, true).slideUp(function() {
```

2018-12-11 16:06 UTC, moloko commented on js/adapt-youtube.js
> +                $transcriptBodyContainer.slideDown(function() {
```suggestion
                $transcriptBodyContainer.stop(true, true).slideDown(function() {
```

2018-12-11 16:12 UTC, moloko commented
@mike-st have resolved the conflicts for you... was there a reason you set the FW dependency to a min of 2.0.9? if so, let me know - happy to change this back.

2018-12-13 13:51 UTC, mike-st commented
Hi @moloko Thanks for the updates and fixes I will take a look at it soon. Makes sense from what I can tell so far. Appreciate your help. Framework 2.0.9 is the oldest one we work with so I just set it to that and above as we have a couple of instances running different framework versions. You can omit that one.

2018-12-13 13:51 UTC, closed without merging

2018-12-14 18:10 UTC, moloko commented
@mike-st if you want to leave the FW dependency as-is that's fine, I can always change it in our branch after merging the PR. Whatever's easiest for you.